# Generated by Django 3.1.6 on 2021-02-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210217_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('INFO', '정보'), ('COMMUNICATE', '소통해요'), ('VISIT', '가봤어요'), ('BUY', '사봤어요'), ('NOTICE', '공지해요')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ratedpost',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='평점'),
        ),
    ]
