# Generated by Django 3.1.6 on 2021-02-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_askpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AskPost',
        ),
    ]
