# Generated by Django 3.1.6 on 2021-02-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='FCM_token',
        ),
    ]
