# Generated by Django 3.1.6 on 2021-02-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210217_2100'),
        ('users', '0003_remove_user_fcm_token'),
    ]

    operations = [
    ]
