# Generated by Django 3.1.6 on 2021-02-10 22:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AskPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='상품명')),
                ('company', models.CharField(max_length=120, verbose_name='제조사')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='문의 내용')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
