# Generated by Django 3.1.6 on 2021-02-14 16:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipOffPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prdlstReportNo', models.PositiveIntegerField(default=0, verbose_name='상품번호')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='제보 내용')),
                ('is_checked', models.BooleanField(default=False, verbose_name='확인 여부')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
